language: node_js
node_js:
- '8.9'
branches:
  only:
  - development
before_script:
- npm install typescript
- npm install -g cordova ionic
script:
- ionic build --prod
notifications:
  email:
    on_failure: change
    on_success: change
